name: browser_test
author: "Pete Blois <pete@blois.us>"
homepage: https://github.com/blois/
description: Dart unit tests configuration for browser testing
version: 0.0.1
dependencies:
  unittest: ">=0.4.5"
  browser: any
environment:
  sdk: ">=0.4.6"
